name: Upgrade dependencies
on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:
  pull_request:
    paths:
    - .github/renovate.json
    - .github/workflows/renovate.yml

jobs:
  upgrade:
    name: Upgrade dependencies
    runs-on: ubuntu-latest
    env:
      RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' }}
      RENOVATE_ONBOARDING: false
      RENOVATE_REPOSITORIES: ${{ github.repository }}
      LOG_LEVEL: debug
    steps:
    - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
      id: app-token
      with:
        app-id: ${{ secrets.RENOVATE_APP_ID }}
        private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
        permission-contents: write
        permission-issues: write
        permission-workflows: write
        # When run from a PR, it should be in dry-run mode, so shouldn't create PRs.
        # But if it did, it's not too hard to imagine a PR creation loop. So
        # let's add another layer of protection.
        permission-pull-requests: "${{ github.event_name == 'pull_request' && 'read' || 'write' }}"
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: renovatebot/github-action@68a3ea99af6ad249940b5a9fdf44fc6d7f14378b # v46.1.6
      with:
        token: ${{ steps.app-token.outputs.token }}
